version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: banking_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Jobs@123
      POSTGRES_DB: banking_db<.
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
